# OSS-DBS is tested for Python >= 3.8

stages:
    - "test"
    - "run"
    - "pages"

.test:
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install tox
    - tox -e $PYTHONVERSION

.run:
  script:
   - pip install virtualenv
   - virtualenv venv
   - source venv/bin/activate
   - pip install .
   - cd input_files
   - ossdbs 'inputTest.json'

test-3.8:
   extends: ".test"
   stage: "test"
   variables:
           PYTHONVERSION: "py38"
   image: "python:3.8"

run-3.8:
   extends: ".run"
   stage: "run"
   image: "python:3.8"

test-3.9:
   extends: ".test"
   stage: "test"
   variables:
           PYTHONVERSION: "py39"
   image: "python:3.9"

run-3.9:
   extends: ".run"
   stage: "run"
   image: "python:3.9"

test-3.10:
   extends: ".test"
   stage: "test"
   variables:
           PYTHONVERSION: "py310"
   image: "python:3.10"

run-3.10:
   extends: ".run"
   stage: "run"
   image: "python:3.10"

pages:
  stage: "pages"
  # needed with jupyter notebooks
  # image: "ubuntu:22.04"
  image: "python:3.10"
  script:
    # needed for jupyter notebooks
    # - apt update
    # - apt install -y python3 python3-pip
    # - apt install -y pandoc
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install .
    - cd docs
    - pip install -r requirements.txt
    # in future also include jupyter notebooks
    # - jupyter --version
    # - jupyter nbextension install --user --py widgetsnbextension
    # - jupyter nbextension enable --user --py widgetsnbextension
    # - jupyter nbextension install --user --py webgui_jupyter_widgets
    # - jupyter nbextension enable --user --py webgui_jupyter_widgets
    - make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only: 
      - main
