# OSS-DBS is tested for Python >= 3.8

stages:
    - "test"
    - "run"
    - "pages"

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

.test:
  script:
    - pip install tox
    - tox -e $PYTHONVERSION

.run:
  script:
   - pip install .
   - python3 -c "import ossdbs"
   - python3 -c "import ossdbs.dielectric_model"
   - python3 -c "from ossdbs.brain_model import BrainModel"
   #- cd ossdbs/scripts
   #- python3 ossdbs 


test-3.8:
   extends: ".test"
   stage: "test"
   variables:
           PYTHONVERSION: "py38"
   image: "python:3.8"

run-3.8:
   extends: ".run"
   stage: "run"
   image: "python:3.8"

test-3.9:
   extends: ".test"
   stage: "test"
   variables:
           PYTHONVERSION: "py39"
   image: "python:3.9"

run-3.9:
   extends: ".run"
   stage: "run"
   image: "python:3.9"

test-3.10:
   extends: ".test"
   stage: "test"
   variables:
           PYTHONVERSION: "py310"
   image: "python:3.10"

run-3.10:
   extends: ".run"
   stage: "run"
   image: "python:3.10"

pages:
  stage: "pages"
  image: "python:3.10"
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs
    - make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only: 
      - revision 
  # rules:
    #    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
