"""Generate paraview_camera.py from an OSS-DBS settings JSON.

OSS-DBS does not depend on ParaView at runtime — this script reads
the electrode geometry from a settings JSON and emits a small
Python module with slice + camera constants. Both render scripts
(`render_figures.py` for pvbatch and `render_figures_pyvista.py`)
import that module, so they automatically follow whatever electrode
the JSON describes.

Usage:

    python generate_paraview_camera.py                       # base_settings.json
    python generate_paraview_camera.py --settings other.json
    python generate_paraview_camera.py --lead-offset-mm 3.25 # anchor on contacts
"""

import argparse
import json
from pathlib import Path

import numpy as np


def _read_vec(d: dict) -> np.ndarray:
    return np.array([d["x[mm]"], d["y[mm]"], d["z[mm]"]], dtype=float)


def _normalize(v: np.ndarray) -> np.ndarray:
    return v / np.linalg.norm(v)


def _perpendicular_to(direction: np.ndarray) -> np.ndarray:
    """Unit vector perpendicular to ``direction``, well-conditioned for any axis."""
    helper = np.eye(3)[int(np.argmin(np.abs(direction)))]
    return _normalize(np.cross(direction, helper))


def derive_view(
    settings: dict,
    parallel_scale: float,
    camera_offset: float,
    lead_offset_mm: float | None,
) -> dict:
    """Derive slice + camera from electrode geometry."""
    elec = settings["Electrodes"][0]
    direction = _normalize(_read_vec(elec["Direction"]))
    if lead_offset_mm is None:
        origin = _read_vec(settings["BrainRegion"]["Center"])
    else:
        origin = _read_vec(elec["TipPosition"]) + lead_offset_mm * direction
    normal = _perpendicular_to(direction)
    return {
        "slice_origin": origin,
        "slice_normal": normal,
        "camera_view_up": direction,
        "camera_focal_point": origin,
        "camera_position": origin + camera_offset * normal,
        "camera_parallel_scale": parallel_scale,
    }


TEMPLATE = '''\
"""Auto-generated by generate_paraview_camera.py — do not edit by hand.

Slice plane and camera constants derived from {settings_name!r}.
Regenerate with:
    python generate_paraview_camera.py --settings {settings_name!r}{extra_args}
"""

# Slice plane (origin on the lead axis, normal perpendicular to it,
# so the cut plane contains the lead).
SLICE_ORIGIN = {slice_origin}
SLICE_NORMAL = {slice_normal}

# Camera — parallel projection. View-up = lead direction so the lead
# is vertical on screen; focal point on the slice plane; position
# offset along the slice normal so we look straight at the cut.
CAMERA_FOCAL_POINT = {camera_focal_point}
CAMERA_POSITION = {camera_position}
CAMERA_VIEW_UP = {camera_view_up}
CAMERA_PARALLEL_SCALE = {camera_parallel_scale!r}
'''


def _fmt(v: np.ndarray) -> str:
    return "({:.6f}, {:.6f}, {:.6f})".format(*v)


def main() -> None:
    """The main function to generate Paraview camera."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--settings", default="base_settings.json")
    parser.add_argument("--out", default="paraview_camera.py")
    parser.add_argument("--parallel-scale", type=float, default=13.0)
    parser.add_argument("--camera-offset", type=float, default=50.0)
    parser.add_argument(
        "--lead-offset-mm",
        type=float,
        default=None,
        help="Anchor at tip + offset*direction. Defaults to BrainRegion.Center.",
    )
    args = parser.parse_args()

    settings = json.loads(Path(args.settings).read_text())
    view = derive_view(
        settings, args.parallel_scale, args.camera_offset, args.lead_offset_mm
    )

    extra_args = ""
    if args.parallel_scale != 13.0:
        extra_args += f" --parallel-scale {args.parallel_scale}"
    if args.camera_offset != 50.0:
        extra_args += f" --camera-offset {args.camera_offset}"
    if args.lead_offset_mm is not None:
        extra_args += f" --lead-offset-mm {args.lead_offset_mm}"

    text = TEMPLATE.format(
        settings_name=args.settings,
        extra_args=extra_args,
        slice_origin=_fmt(view["slice_origin"]),
        slice_normal=_fmt(view["slice_normal"]),
        camera_focal_point=_fmt(view["camera_focal_point"]),
        camera_position=_fmt(view["camera_position"]),
        camera_view_up=_fmt(view["camera_view_up"]),
        camera_parallel_scale=view["camera_parallel_scale"],
    )
    Path(args.out).write_text(text)
    print(f"wrote {args.out} from {args.settings}")


if __name__ == "__main__":
    main()
