"""Auto-generated by generate_paraview_camera.py — do not edit by hand.

Slice plane and camera constants derived from 'base_settings.json'.
Regenerate with:
    python generate_paraview_camera.py --settings 'base_settings.json'
                                       --lead-offset-mm 8.0
"""

# Slice plane (origin on the lead axis, normal perpendicular to it,
# so the cut plane contains the lead).
SLICE_ORIGIN = (13.870937, -12.330716, -4.372988)
SLICE_NORMAL = (0.000000, 0.844697, -0.535245)

# Camera — parallel projection. View-up = lead direction so the lead
# is vertical on screen; focal point on the slice plane; position
# offset along the slice normal so we look straight at the cut.
CAMERA_FOCAL_POINT = (13.870937, -12.330716, -4.372988)
CAMERA_POSITION = (13.870937, 29.904114, -31.135260)
CAMERA_VIEW_UP = (0.302733, 0.510129, 0.805060)
CAMERA_PARALLEL_SCALE = 13.0
