from .abbott_stjude import (
    AbbottStJudeActiveTipModel,
    AbbottStJudeActiveTipParameters,
    AbbottStJudeDirectedModel,
    AbbottStJudeParameters,
)
from .boston_scientific_vercise import (
    BostonScientificVerciseDirectedModel,
    BostonScientificVerciseDirectedParameters,
    BostonScientificVerciseModel,
    BostonScientificVerciseParameters,
)
from .defaults import (
    AbbottStJudeActiveTip6142_6145,
    AbbottStJudeActiveTip6146_6149,
    AbbottStJudeDirected6172,
    AbbottStJudeDirected6173,
    BostonScientificVercise,
    BostonScientificVerciseDirected,
    DixiSEEG10,
    DixiSEEG15,
    Medtronic3387,
    Medtronic3389,
    Medtronic3391,
    MedtronicSenSightB33005,
    MedtronicSenSightB33015,
    MicroElectrode,
    MicroProbesRodentElectrode,
    MicroProbesSNEX100,
    PINSMedicalL301,
    PINSMedicalL302,
    PINSMedicalL303,
    default_electrode_parameters,
)
from .dixi_microtechniques import (
    DixiSEEG10Model,
    DixiSEEG15Model,
    DixiSEEG10Parameters,
    DixiSEEG15Parameters,
    )
from .electrode_model_template import ElectrodeModel
from .medtronic import (
    MedtronicModel,
    MedtronicParameters,
    MedtronicSenSightModel,
)
from .microelectrode import MicroElectrodeModel, MicroElectrodeParameters
from .micro_probes import (
    MicroProbesRodentElectrodeModel,
    MicroProbesRodentElectrodeParameters,
    MicroProbesSNEX100Model,
    MicroProbesSNEX100Parameters,
)
from .pins_medical import PINSMedicalModel, PINSMedicalParameters

ELECTRODES = {
    "AbbottStJudeActiveTip6142_6145": AbbottStJudeActiveTip6142_6145,
    "AbbottStJudeActiveTip6146_6149": AbbottStJudeActiveTip6146_6149,
    "AbbottStJudeDirected6172": AbbottStJudeDirected6172,
    "AbbottStJudeDirected6173": AbbottStJudeDirected6173,
    "BostonScientificVercise": BostonScientificVercise,
    "BostonScientificVerciseDirected": BostonScientificVerciseDirected,
    "DixiSEEG10": DixiSEEG10,
    "DixiSEEG15": DixiSEEG15,
    "Medtronic3387": Medtronic3387,
    "Medtronic3389": Medtronic3389,
    "Medtronic3391": Medtronic3391,
    "MedtronicSenSightB33015": MedtronicSenSightB33015,
    "MedtronicSenSightB33005": MedtronicSenSightB33005,
    "MicroElectrode": MicroElectrode,
    "MicroProbesSNEX100": MicroProbesSNEX100,
    "PINSMedicalL301": PINSMedicalL301,
    "PINSMedicalL302": PINSMedicalL302,
    "PINSMedicalL303": PINSMedicalL303,
    "MicroProbesRodentElectrode": MicroProbesRodentElectrode,
}

ELECTRODE_MODELS = {
    "AbbottStJudeActiveTipCustom": AbbottStJudeActiveTipModel,
    "AbbottStJudeDirectedCustom": AbbottStJudeDirectedModel,
    "BostonScientificVerciseCustom": BostonScientificVerciseModel,
    "BostonScientificVerciseDirectedCustom": BostonScientificVerciseDirectedModel,
    "DixiSEEG10Custom": DixiSEEG10Model,
    "DixiSEEG15Custom": DixiSEEG15Model,
    "MedtronicCustom": MedtronicModel,
    "MedtronicSensightCustom": MedtronicSenSightModel,
    "MicroElectrodeCustom": MicroElectrodeModel,
    "MicroProbesRodentElectrodeCustom": MicroProbesRodentElectrodeModel,
    "MicroProbesSNEX100Custom": MicroProbesSNEX100Model,
    "PINSMedicalCustom": PINSMedicalModel,
}


ELECTRODE_PARAMETERS = {
    "AbbottStJudeActiveTipModel": AbbottStJudeActiveTipParameters,
    "AbbottStJudeDirectedModel": AbbottStJudeParameters,
    "BostonScientificVerciseModel": BostonScientificVerciseParameters,
    "BostonScientificVerciseDirectedModel": BostonScientificVerciseDirectedParameters,
    "DixiSEEG10Model": DixiSEEG10Parameters,
    "DixiSEEG15Model": DixiSEEG15Parameters,
    "MedtronicModel": MedtronicParameters,
    "MedtronicSenSightModel": MedtronicParameters,
    "MicroElectrodeModel": MicroElectrodeParameters,
    "MicroProbesRodentElectrodeModel": MicroProbesRodentElectrodeParameters,
    "MicroProbesSNEX100Model": MicroProbesSNEX100Parameters,
    "PINSMedicalModel": PINSMedicalParameters,
}

__all__ = (
    "ElectrodeModel",
    "AbbottStJudeActiveTip6142_6145",
    "AbbottStJudeActiveTip6146_6149",
    "AbbottStJudeActiveTipModel",
    "AbbottStJudeDirected6172",
    "AbbottStJudeDirected6173",
    "AbbottStJudeDirectedModel",
    "AbbottStJudeActiveTipParameters",
    "AbbottStJudeParameters",
    "BostonScientificVercise",
    "BostonScientificVerciseDirected",
    "BostonScientificVerciseModel",
    "BostonScientificVerciseDirectedModel",
    "BostonScientificVerciseParameters",
    "BostonScientificVerciseDirectedParameters",
    "DixiSEEG10",
    "DixiSEEG15",
    "DixiSEEG10Model",
    "DixiSEEG15Model",
    "DixiSEEG10Parameters",
    "DixiSEEG15Parameters",
    "Medtronic3387",
    "Medtronic3389",
    "Medtronic3391",
    "MedtronicModel",
    "MedtronicSenSightB33015",
    "MedtronicSenSightB33005",
    "MedtronicParameters",
    "MicroElectrode",
    "MicroElectrodeModel",
    "MicroElectrodeParameters",
    "MicroProbesRodentElectrode",
    "MicroProbesRodentElectrodeModel",
    "MicroProbesRodentElectrodeParameters",
    "MicroProbesSNEX100",
    "MicroProbesSNEX100Model",
    "MicroProbesSNEX100Parameters",
    "PINSMedicalL301",
    "PINSMedicalL302",
    "PINSMedicalL303",
    "PINSMedicalModel",
    "PINSMedicalParameters",
    "default_electrode_parameters",
)
